edition = "2024"
max_width = 119
hard_tabs = false
tab_spaces = 4
newline_style = "Auto"
use_small_heuristics = "Default"
reorder_imports = true
reorder_modules = true
remove_nested_parens = true
force_explicit_abi = true
merge_derives = false
use_field_init_shorthand = true
use_try_shorthand = true
fn_params_layout = "Tall"
