[package]
name = "usereport-rs"
version = "0.0.1"
authors = ["Lukas Pustina <lukas@pustina.net>"]
description = "Collect information for Linux Performance Analysis in 60,000 Milliseconds"
repository = "https://github.com/lukaspustina/usereport-es.git"
documentation = "https://github.com/lukaspustina/usereport-es.git"
readme = "README.md"
license = "MIT"
keywords = ["performance", "analysis", "sre"]
categories = ["command-line-utilities" ]
include = [
  "README.md",
  "LICENSE",
  "**/*.rs",
  "Cargo.toml",
]
edition = "2018"

[badges]

[features]
bin = []

[[bin]]
name = "usereport"
path = "src/bin/usereport.rs"
doc = false
required-features = ["bin"]

[lib]
name = "usereport"
path = "src/lib.rs"

[[example]]
name = "json_report"

[dependencies]
log = "0.4"
handlebars = "2.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
snafu = "0.6"
subprocess = "0.1"
toml = "0.5"

[dev-dependencies]
env_logger = "0.7"
spectral = "0.6"

