[package]
name = "usereport-rs"
version = "0.1.1"
authors = ["Lukas Pustina <lukas@pustina.net>"]
description = "Collect system information for the first 60 seconds of a performance analysis"
repository = "https://github.com/lukaspustina/usereport-rs.git"
documentation = "https://github.com/lukaspustina/usereport-rs.git"
readme = "README.md"
license = "MIT"
keywords = ["performance", "analysis", "sre"]
categories = ["command-line-utilities" ]
include = [
  "README.md",
  "LICENSE",
  "**/*.rs",
  "Cargo.toml",
]
edition = "2018"

[badges]

[features]
bin = ["atty", "env_logger", "exitfailure", "failure", "human-panic", "indicatif", "prettytable-rs", "structopt"]

[[bin]]
name = "usereport"
path = "src/bin/usereport.rs"
doc = false
required-features = ["bin"]

[lib]
name = "usereport"
path = "src/lib.rs"

[[example]]
name = "json_report"
required-features = ["bin"]

[[example]]
name = "md_report"
required-features = ["bin"]

[dependencies]
atty = { version = "0.2", optional = true }
chrono = { version = "0.4", features = ["serde"] }
env_logger = { version = "0.7", optional = true }
exitfailure = { version = "0.5", optional = true }
failure = { version = "0.1", optional = true }
handlebars = "2.0"
human-panic = { version = "1", optional = true }
indicatif = { version = "0.13", optional = true }
log = "0.4"
prettytable-rs = { version = "0.8", optional = true }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
shellwords = "1"
snafu = "0.6"
structopt = { version = "0.3.7", optional = true }
subprocess = "0.1"
toml = "0.5"
uname = "0.1"

[dev-dependencies]
env_logger = "0.7"
spectral = "0.6"

